# Nombre del flujo de trabajo
name: Deploy to Firebase Hosting

# Define cu치ndo se ejecutar치 la acci칩n
on:
  push:
    branches:
      - main  # Se ejecuta cada vez que haces push a la rama 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Se ejecuta en un servidor virtual con Ubuntu

    steps:
      # 1. Clona tu repositorio en el servidor virtual
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Inject Firebase configuration
      - name: Inject Firebase Config
        run: |
          cat > public/firebase-config.js << EOF
          window.FIREBASE_CONFIG = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          };
          EOF

      # 3. Configura la acci칩n para desplegar en Firebase
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADMINISTRACIONPRONOSTICOS }}'
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
